### ISSUE TITLE
Error Messages in log

### ISSUE THREAD

**Issue by snai** [franc-carter/fhem-lifx#2]
I have set up a LIFX Bulb in FHEM with the following parameters in fhem.cgf:

```
### LIFX
define lifx LIFXBridge
define name LIFXBulb label_name|XX:XX:XX:XX:XX
attr name IODev lifx
attr name room livingroom
```

It is possible to switch the bulb off and on (sometimes with a very long lag), but my log is filled with this message:

```
lifx: Unknown code Device::LIFX::Message=HASH(0x2117da0), help me!
```

**Comment by franc-carter** [comment]
The line "attr name IODev lifx" should be "attr IODev lifx", but I doubt that's causing the  'Unkown code' message - I'll have a look in to that

**Comment by snai** [comment]
I changed the line to 

```
"attr IODev lifx"
```

but the error still occurs. Thanks for looking into it!

**Comment by franc-carter** [comment]
I thing I have fixed the log message now, try the latest vesion

**Comment by snai** [comment]
Sorry I have forgotten to close the issue.
It's working now. Thank's for the fast response!
